"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
type Profile={level:string;interactions:number;domains:Record<string,number>};
const fallback:Profile={level:"simple",interactions:0,domains:{macro:10,markets:10,companies:10,fundamentals:5,technical:0,statistics:0,bonds:0,currency:5}};
const paths=[
 {n:"01",title:"Understand India",text:"Start with growth, jobs, inflation, rates, currency and trade — in normal language.",href:"/economy?ask=I am a beginner. Teach me how India works as an economy and give me one simple experiment."},
 {n:"02",title:"Follow one change",text:"Pick a shock such as crude oil, rates or the rupee and follow where the effect travels.",href:"/economy?ask=Give me one important economic change to explore and walk me through its cause and effect."},
 {n:"03",title:"Open a sector",text:"See which part of India feels the change and why it matters to people and businesses.",href:"/#sectors"},
 {n:"04",title:"Understand a company",text:"Use GAJA to understand the business before ratios or price predictions.",href:"/market-lens"}
];
export default function LearningJourney(){
 const [p,setP]=useState<Profile>(fallback);
 useEffect(()=>{const load=(x?:any)=>{try{const raw=localStorage.getItem("indiaLensLearningProfile");setP(x||(raw?JSON.parse(raw):fallback))}catch{}};load();const fn=(e:any)=>load(e.detail);window.addEventListener("india-lens-learning-change",fn);return()=>window.removeEventListener("india-lens-learning-change",fn)},[]);
 const values=Object.values(p.domains||{});const score=Math.round(values.reduce((a:number,b:any)=>a+Number(b||0),0)/Math.max(1,values.length));
 const next=p.interactions<2?0:(p.domains?.macro||0)<25?0:(p.domains?.statistics||0)<20?1:(p.domains?.markets||0)<25?2:3;
 return <section className="learningJourney">
   <div className="journeyIntro"><div><small>YOUR INDIA JOURNEY</small><h2>Learn the country by following cause and effect.</h2><p>India Lens becomes deeper as you learn. You never need to begin with finance vocabulary.</p></div><div className="journeyProgress"><b>{score}%</b><span>current learning depth</span><i><em style={{width:Math.max(6,score)+"%"}}/></i><small>{p.interactions} guided interactions · {p.level||"simple"} mode</small></div></div>
   <div className="journeyPath">{paths.map((x,i)=><Link key={x.n} href={x.href} className={i===next?"next":""}><em>{x.n}</em><small>{i<next?"EXPLORED":i===next?"TRY THIS NEXT":"AHEAD"}</small><h3>{x.title}</h3><p>{x.text}</p><span>{i===next?"Continue learning →":"Open →"}</span></Link>)}</div>
   <div className="journeyRule"><b>One rule:</b> Every screen should answer <strong>“What does this mean in the real world?”</strong> before showing deeper market language.</div>
   <style jsx global>{`.learningJourney{padding:72px 8vw;background:#e6e1d5;border-top:1px solid #c7c2b5;border-bottom:1px solid #c7c2b5}.journeyIntro{display:grid;grid-template-columns:1.4fr .6fr;gap:50px;align-items:end;margin-bottom:28px}.journeyIntro small{font-size:9px;letter-spacing:2px;color:#c65b2a;font-weight:700}.journeyIntro h2{font:clamp(32px,4vw,52px) Georgia,serif;line-height:1.05;margin:9px 0 12px}.journeyIntro p{max-width:700px;color:#62665f;line-height:1.6}.journeyProgress{border-left:1px solid #aaa598;padding-left:24px}.journeyProgress>b{display:block;font:38px Georgia,serif}.journeyProgress>span,.journeyProgress>small{display:block;font-size:9px;color:#74786f;letter-spacing:.7px}.journeyProgress>i{display:block;height:5px;background:#c6c1b4;margin:12px 0}.journeyProgress>i>em{display:block;height:100%;background:#496d4c}.journeyPath{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;background:#aaa69a;border:1px solid #aaa69a}.journeyPath>a{background:#f1ede3;padding:22px;min-height:245px;position:relative}.journeyPath>a.next{background:#151914;color:#f3f0e7}.journeyPath>a>em{font:25px Georgia,serif;color:#b1aca0;font-style:normal}.journeyPath>a.next>em{color:#d87946}.journeyPath>a>small{float:right;font-size:7px;letter-spacing:1.2px;color:#8a8e86}.journeyPath>a.next>small{color:#d87946}.journeyPath h3{font:24px Georgia,serif;margin:32px 0 9px}.journeyPath p{font-size:11px;line-height:1.55;color:#656961}.journeyPath a.next p{color:#aeb5ad}.journeyPath a>span{position:absolute;bottom:20px;font-size:9px;color:#b5522b}.journeyPath a.next>span{color:#e79262}.journeyRule{margin-top:16px;padding:15px 18px;border-left:3px solid #496d4c;background:#efebe1;font-size:12px;line-height:1.6}@media(max-width:850px){.journeyIntro{grid-template-columns:1fr}.journeyPath{grid-template-columns:1fr 1fr}}@media(max-width:520px){.learningJourney{padding:52px 6vw}.journeyPath{grid-template-columns:1fr}.journeyPath>a{min-height:190px}.journeyProgress{border-left:0;border-top:1px solid #aaa598;padding:18px 0 0}}`}</style>
 </section>
}
