export type Sector={slug:string;name:string;summary:string;industries:string[];drivers:string[];risks:string[]};
export const sectors:Sector[]=[
{slug:"financials",name:"Financials",summary:"Banks, NBFCs, insurance and capital markets",industries:["Private Banks","Public Banks","NBFC","Insurance","Capital Markets"],drivers:["Credit growth","Financialisation","Investment cycle"],risks:["Asset quality","Liquidity","Rate shocks"]},
{slug:"technology",name:"Technology",summary:"IT services, software, electronics and digital platforms",industries:["IT Services","Software","Electronics","SaaS","Digital Platforms"],drivers:["Digital adoption","Exports","AI investment"],risks:["Global demand","Skills","Valuation cycles"]},
{slug:"energy",name:"Energy",summary:"Oil, gas, refining, renewables and integrated energy",industries:["Oil & Gas","Refining","Gas","Renewables","Storage"],drivers:["Energy demand","Refining margins","Energy transition"],risks:["Import prices","Regulation","Commodity cycles"]},
{slug:"automobiles",name:"Automobiles",summary:"Passenger vehicles, two-wheelers, commercial vehicles and components",industries:["Passenger Vehicles","Two Wheelers","Commercial Vehicles","Auto Components","EV"],drivers:["Income growth","Replacement demand","EV adoption"],risks:["Input costs","Financing","Technology shifts"]},
{slug:"consumer-staples",name:"Consumer Staples",summary:"FMCG, food, beverages and household consumption",industries:["FMCG","Foods","Beverages","Personal Care","Household Products"],drivers:["Income","Rural demand","Distribution"],risks:["Input inflation","Demand slowdown","Competition"]},
{slug:"consumer-discretionary",name:"Consumer Discretionary",summary:"Retail, jewellery, hotels, restaurants and lifestyle spending",industries:["Retail","Jewellery","Hotels","Restaurants","Lifestyle"],drivers:["Disposable income","Urbanisation","Premiumisation"],risks:["Consumer slowdown","Valuation","Execution"]},
{slug:"industrials",name:"Industrials",summary:"Engineering, automation, electrical equipment and capital goods",industries:["Engineering","Automation","Electrical Equipment","Capital Goods","Industrial Machinery"],drivers:["Capex","Manufacturing expansion","Infrastructure"],risks:["Execution","Cycles","Input costs"]},
{slug:"materials",name:"Materials",summary:"Steel, aluminium, mining, cement and other materials",industries:["Steel","Aluminium","Mining","Cement","Diversified Metals"],drivers:["Construction","Capex","Commodity demand"],risks:["Commodity prices","China demand","Energy costs"]},
{slug:"healthcare",name:"Healthcare",summary:"Pharma, hospitals, diagnostics and life sciences",industries:["Pharma","Hospitals","Diagnostics","CRAMS","Devices"],drivers:["Income","Insurance","Export demand"],risks:["Regulation","Pricing","R&D execution"]},
{slug:"telecom",name:"Telecom",summary:"Telecom services, towers, fibre and communications equipment",industries:["Telecom Services","Towers","Enterprise Networks","Fibre","Telecom Equipment"],drivers:["Data consumption","5G","Enterprise digitisation"],risks:["Capex intensity","Competition","Regulation"]},
{slug:"utilities",name:"Utilities",summary:"Power generation, transmission, distribution and renewables",industries:["Generation","Transmission","Distribution","Hydro","Renewables"],drivers:["Electricity demand","Grid investment","Electrification"],risks:["Fuel supply","Tariffs","Project economics"]},
{slug:"real-estate",name:"Real Estate",summary:"Residential, commercial and retail property",industries:["Residential","Commercial","Retail Real Estate","REITs","Building Products"],drivers:["Urbanisation","Mortgage demand","Office absorption"],risks:["Rates","Inventory","Execution"]},
{slug:"defence",name:"Defence",summary:"Aerospace, electronics, shipbuilding and defence systems",industries:["Aerospace","Defence Electronics","Shipbuilding","Missiles","Land Systems"],drivers:["Indigenisation","Procurement","Exports"],risks:["Order timing","Execution","Policy concentration"]},
{slug:"infrastructure",name:"Infrastructure",summary:"Roads, rail, ports, logistics and public infrastructure",industries:["Roads","Railways","Ports","Logistics","Construction"],drivers:["Public capex","Urbanisation","Freight growth"],risks:["Execution","Leverage","Commodity costs"]},
{slug:"chemicals",name:"Chemicals",summary:"Specialty chemicals, agrochemicals and process industries",industries:["Specialty Chemicals","Agrochemicals","Fluorochemicals","Industrial Chemicals","Adhesives"],drivers:["Import substitution","Exports","Specialisation"],risks:["Raw materials","Global cycles","Environmental regulation"]},
{slug:"agriculture",name:"Agriculture",summary:"Agri inputs, food processing, rural economy and farm-linked businesses",industries:["Agri Inputs","Fertilisers","Agribusiness","Sugar","Aquaculture"],drivers:["Productivity","Rural income","Formal supply chains"],risks:["Weather","Commodity prices","Policy"]},
{slug:"media",name:"Media",summary:"Broadcasting, cinema, gaming, music and digital entertainment",industries:["Broadcasting","Cinema","Gaming","Music","Digital Media"],drivers:["Advertising","Digital consumption","Premium content"],risks:["Fragmentation","Ad cycles","Content costs"]}
];
export function getSector(slug:string){return sectors.find((sector)=>sector.slug===slug);}
